### PR TITLE
add branch for kodi v19 matrix

### PR DESCRIPTION
**Pull request by aroth-arsoft**

### CODE REVIEW

**Comment by Gomez** [comment]
@aroth-arsoft Does kodi compiled for you? (with this changes)

**Comment by aroth-arsoft** [comment]
> @aroth-arsoft Does kodi compiled for you? (with this changes)
The last time i tried to build this docker image was about 12 month ago. I think kodi 19 wasn't released as stable at the point.

**Comment by Gomez** [comment]
Ok, you still interested in getting this PR ready? I struggle to get Kodi compiled, but i can help create a follow up PR with the new headless patch.

**Comment by aroth-arsoft** [comment]
> Ok, you still interested in getting this PR ready? I struggle to get Kodi compiled, but i can help create a follow up PR with the new headless patch.

Sorry, but i'm lost interest in this issue and struggling to find time to get this ready.

**Pull request closed without merging**
